/**
 * Active dataset + resolved copy for the dashboard.
 *
 * Three inputs come together here:
 *   - `data/<topic>.json`  - the pulled NUMBERS (regenerated by `npm run pull`)
 *   - `config/content.ts`  - the authored WORDS (never touched by the pull)
 *   - `config/subjects.ts` - which topic is active + each subject's color
 *
 * `ACTIVE_TOPIC` selects one topic; this module merges its pulled entities with
 * the authored playbooks (falling back to a plain, no-LLM summary when a subject
 * has none) and fills the copy tokens. Every section renders from `entities` and
 * `content` below - swap the topic and the whole dashboard follows.
 */

import type { Dataset, Entity, EntityData, Platform, Playbook } from "./types";
import { computeStats } from "./metrics";
import { formatCompact, PLATFORM_LABELS } from "./format";
import { brand } from "@/config/brand";
import { ACTIVE_TOPIC } from "@/config/subjects";
import { CONTENT, DEFAULT_CONTENT } from "@/config/content";
import watchesData from "@/data/watches.json";

/** Every generated dataset the app knows about. Add a line per new topic. */
const DATASETS: Record<string, Dataset> = {
  watches: watchesData as unknown as Dataset,
};

const dataset = DATASETS[ACTIVE_TOPIC];
if (!dataset) {
  throw new Error(
    `No dataset for "${ACTIVE_TOPIC}". Run \`npm run pull\` to generate data/${ACTIVE_TOPIC}.json.`,
  );
}

const override = CONTENT[ACTIVE_TOPIC] ?? {};
const masthead = override.masthead ?? DEFAULT_CONTENT.masthead;
const sections = override.sections ?? DEFAULT_CONTENT.sections;
const footer = override.footer ?? DEFAULT_CONTENT.footer;
const playbooks = override.playbooks ?? {};

const baseEntities: EntityData[] = dataset.entities;

/** Platform display order for the summary stat bars. */
export const PLATFORM_ORDER: Platform[] = [
  "tiktok",
  "instagram",
  "reddit",
  "pinterest",
  "x",
];

/** Accent color per platform, used in the summary breakdown bars. */
export const PLATFORM_COLORS: Record<Platform, string> = {
  tiktok: "#e8e9ea",
  instagram: "#c98fd6",
  reddit: "#ef8a5f",
  pinterest: "#e0526f",
  x: "#8f929e",
};

/** Week buckets for the weekly-pulse trend chart, oldest first. */
export const WEEK_LABELS: string[] = dataset.weekLabels;

// Merge authored/fallback playbooks onto the pulled entities

const stats = computeStats(baseEntities as unknown as Entity[]);

/**
 * A plain, no-LLM playbook built from a subject's own numbers - used when
 * `config/content.ts` has no authored playbook for that subject.
 */
function fallbackPlaybook(e: EntityData): Playbook {
  const share = stats[e.id]?.sharePct ?? 0;
  const topNarrative = e.narratives[0];
  const topPost = [...e.posts].sort((a, b) => b.views - a.views)[0];
  const topTag = e.whitespace[0];

  const drivers: string[] = [];
  if (topNarrative) {
    drivers.push(
      `Its biggest content cluster is "${topNarrative.label}" (${topNarrative.count} posts).`,
    );
  }
  if (topPost) {
    drivers.push(
      `Its single biggest post pulled ${formatCompact(topPost.views)} views on ${PLATFORM_LABELS[topPost.platform]}.`,
    );
  }
  if (topTag) {
    drivers.push(
      `Highest-premium open tag: #${topTag.tag} (+${topTag.premiumPct}% engagement vs. its baseline).`,
    );
  }

  const counters: string[] = [];
  if (topNarrative) {
    counters.push(
      `The "${topNarrative.label}" format is the most active lane here - worth testing a version against your own catalog.`,
    );
  }
  if (topTag) {
    counters.push(
      `#${topTag.tag} carries a +${topTag.premiumPct}% premium and looks under-served - cheap to claim first.`,
    );
  }

  return {
    headline: `${e.name} holds ${share.toFixed(1)}% share of voice across ${e.metrics.records} sampled posts.`,
    drivers: drivers.length
      ? drivers
      : ["Not enough signal in this pull to summarize."],
    counters: counters.length
      ? counters
      : ["Publish more in the active formats to close ground."],
    caveat: null,
  };
}

/** The active topic's entities, each with a resolved playbook. */
export const entities: Entity[] = baseEntities.map((e) => ({
  ...e,
  playbook: playbooks[e.id] ?? fallbackPlaybook(e),
}));

export function getEntity(id: string): Entity | undefined {
  return entities.find((e) => e.id === id);
}

// Resolved copy (tokens filled from the active dataset)

/** Join names as a readable list: "A", "A and B", "A, B and C". */
function joinList(items: string[]): string {
  if (items.length === 0) return "";
  if (items.length === 1) return items[0];
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

const subjectsLabel = joinList(entities.map((e) => e.name));
const platformsLabel = joinList(
  PLATFORM_ORDER.filter((p) => entities.some((e) => e.platforms[p] > 0)).map(
    (p) => PLATFORM_LABELS[p],
  ),
);

function fill(text: string): string {
  return text
    .replaceAll("{brand}", brand.name)
    .replaceAll("{subjects}", subjectsLabel)
    .replaceAll("{platforms}", platformsLabel);
}

/** Resolved, ready-to-render page copy for the active topic. */
export const content = {
  masthead: {
    eyebrow: fill(masthead.eyebrow),
    headline: masthead.headline,
    description: fill(masthead.description),
  },
  sections,
  footer: fill(footer),
};
