/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GrowthDemo": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "KinetkApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}